### ISSUE TITLE
请求添加“设置发帖默认签名档”功能

### ISSUE THREAD

**Issue by Doublefire-Chen** [wukgdu/bdwm_viewer#1]
如题，谢谢。
PS：最近体验了一下贵APP，各项功能都挺不错的，作者辛苦了。

**Comment by wukgdu** [comment]
诶，一直没加
那就改成发帖的时候选的签名档是默认签名档吧
周日发新版本

**Comment by Doublefire-Chen** [comment]
> 诶，一直没加 那就改成发帖的时候选的签名档是默认签名档吧 周日发新版本

多谢，辛苦了。
