### ISSUE TITLE
flutter版本问题

### ISSUE THREAD

**Issue by Doublefire-Chen** [wukgdu/bdwm_viewer#2]
我目前用的3.7.0，我看你升级到了3.7.2，我尝试了升级，发现3.7.0就是稳定版的最新版，不知道这两个版本区别大不大。

**Comment by wukgdu** [comment]
flutter 的 minor 升级一般有好多bug，几个patch版本后才会修得比较好，修得勤的话可能会一星期一版
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
我是啥时候看到有新的就升级233

**Comment by Doublefire-Chen** [comment]
明白了，我用3.7.0开发问题应该也不大，谢了
